# Generated by Django 4.1 on 2022-09-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slots_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=50)),
                ('PatientHelathHistory', models.TextField()),
                ('PatientPhoneNumber', models.CharField(max_length=15)),
                ('PatientSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slots')),
            ],
        ),
    ]
